package io.soldierinwhite.pillowbarge.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF795900)
val light_onPrimary = Color(0xFFFFFFFF)
val light_primaryContainer = Color(0xFFFFDFA0)
val light_onPrimaryContainer = Color(0xFF261A00)
val light_secondary = Color(0xFF6B5C3F)
val light_onSecondary = Color(0xFFFFFFFF)
val light_secondaryContainer = Color(0xFFF5E0BB)
val light_onSecondaryContainer = Color(0xFF241A04)
val light_tertiary = Color(0xFF4A6546)
val light_onTertiary = Color(0xFFFFFFFF)
val light_tertiaryContainer = Color(0xFFCCEBC4)
val light_onTertiaryContainer = Color(0xFF082008)
val light_error = Color(0xFFBA1A1A)
val light_errorContainer = Color(0xFFFFDAD6)
val light_onError = Color(0xFFFFFFFF)
val light_onErrorContainer = Color(0xFF410002)
val light_background = Color(0xFFFFFBFF)
val light_onBackground = Color(0xFF1E1B16)
val light_surface = Color(0xFFFFFBFF)
val light_onSurface = Color(0xFF1E1B16)
val light_surfaceVariant = Color(0xFFEDE1CF)
val light_onSurfaceVariant = Color(0xFF4D4639)
val light_outline = Color(0xFF7F7667)
val light_inverseOnSurface = Color(0xFFF8EFE7)
val light_inverseSurface = Color(0xFF34302A)
val light_inversePrimary = Color(0xFFFBBC00)
val light_surfaceTint = Color(0xFF795900)
val light_outlineVariant = Color(0xFFD0C5B4)
val light_scrim = Color(0xFF000000)

val dark_primary = Color(0xFFFBBC00)
val dark_onPrimary = Color(0xFF402D00)
val dark_primaryContainer = Color(0xFF5C4300)
val dark_onPrimaryContainer = Color(0xFFFFDFA0)
val dark_secondary = Color(0xFFD8C4A0)
val dark_onSecondary = Color(0xFF3B2F15)
val dark_secondaryContainer = Color(0xFF53452A)
val dark_onSecondaryContainer = Color(0xFFF5E0BB)
val dark_tertiary = Color(0xFFB1CFA9)
val dark_onTertiary = Color(0xFF1D361B)
val dark_tertiaryContainer = Color(0xFF334D30)
val dark_onTertiaryContainer = Color(0xFFCCEBC4)
val dark_error = Color(0xFFFFB4AB)
val dark_errorContainer = Color(0xFF93000A)
val dark_onError = Color(0xFF690005)
val dark_onErrorContainer = Color(0xFFFFDAD6)
val dark_background = Color(0xFF1E1B16)
val dark_onBackground = Color(0xFFE9E1D8)
val dark_surface = Color(0xFF1E1B16)
val dark_onSurface = Color(0xFFE9E1D8)
val dark_surfaceVariant = Color(0xFF4D4639)
val dark_onSurfaceVariant = Color(0xFFD0C5B4)
val dark_outline = Color(0xFF998F80)
val dark_inverseOnSurface = Color(0xFF1E1B16)
val dark_inverseSurface = Color(0xFFE9E1D8)
val dark_inversePrimary = Color(0xFF795900)
val dark_surfaceTint = Color(0xFFFBBC00)
val dark_outlineVariant = Color(0xFF4D4639)
val dark_scrim = Color(0xFF000000)

val transparent = Color(0X00000000)
